eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
microservice:
  payment-service:
    endpoints:
      endpoint:
        uri: http://Payment-Api/payment/payment
  order-service:
    endpoints:
      endpoint:
        uri: http://Order-Api/order
